version: '3.8'

name: exchange-simulator-service
services:
  exchange-simulator:
    container_name: exchange-simulator
    build: .
    volumes:
      - .env:/app/.env
      - ./logs/:/app/logs
    ports:
      - "127.0.0.1:1889:1889"
    entrypoint: ["/bin/sh", "-c", "exec ./run.sh"]
    tty: true
    ipc: host
    networks:
      - epicure

networks:
  epicure:
    external: true
