version: '3.8'

name: exchange-simulator-service
services:
  exchange-simulator:
    container_name: exchange-simulator
    build: .
    ports:
      - "1889:1889"
    entrypoint: ["/bin/sh", "-c", "exec ./run.sh"]
